import React from 'react';
import {
    Moon,
    BookOpen,
    Flame,
    Heart,
    Crown,
    Wand2,
    Coffee,
    Film,
    Flower2,
    Gamepad2,
    Music,
    Utensils,
    Smile,
    Trophy,
    Gift,
    Sun,
    Bell,
    Check,
    Clock,
    Calendar,
    Cat,
    Feather,
    Compass,
    Shield,
    Zap,
    Gem,
} from 'lucide-react';

export const ICON_MAP = {
    // Standard names
    moon: Moon,
    book: BookOpen,
    flame: Flame,
    heart: Heart,
    crown: Crown,
    wand: Wand2,
    coffee: Coffee,
    film: Film,
    flower: Flower2,
    gamepad: Gamepad2,
    music: Music,
    utensils: Utensils,
    smile: Smile,
    trophy: Trophy,
    gift: Gift,
    sun: Sun,
    bell: Bell,
    clock: Clock,
    calendar: Calendar,
    cat: Cat,
    feather: Feather,
    compass: Compass,
    shield: Shield,
    zap: Zap,
    gem: Gem,

    // Fallback mappings
    sparkles: Gift,
    star: Gem,
    '🌙': Moon,
    '✨': Gift,
    '📚': BookOpen,
    '🍿': Film,
    '☕': Coffee,
    '🍷': Utensils,
    '🌹': Flower2,
    '🎮': Gamepad2,
    '🛁': Heart,
    '🍫': Gift,
    '🛋️': Smile,
    '🕯️': Flame,
    '🦇': Compass,
    '🔮': Gem,
    '🧙‍♀️': Wand2,
    '🧛‍♀️': Crown,
    '🐈‍⬛': Cat,
    '🖤': Heart,
};

export const AVAILABLE_AVATAR_ICONS = [
    { id: 'moon', label: 'Lua', icon: Moon },
    { id: 'gem', label: 'Cristal', icon: Gem },
    { id: 'wand', label: 'Varinha', icon: Wand2 },
    { id: 'crown', label: 'Coroa', icon: Crown },
    { id: 'book', label: 'Grimório', icon: BookOpen },
    { id: 'flame', label: 'Vela / Chama', icon: Flame },
    { id: 'heart', label: 'Coração', icon: Heart },
    { id: 'flower', label: 'Rosa', icon: Flower2 },
    { id: 'shield', label: 'Escudo', icon: Shield },
    { id: 'feather', label: 'Pena', icon: Feather },
    { id: 'cat', label: 'Gato', icon: Cat },
    { id: 'compass', label: 'Bússola', icon: Compass },
];

export const AVAILABLE_REWARD_ICONS = [
    { id: 'film', label: 'Filme', icon: Film },
    { id: 'book', label: 'Leitura', icon: BookOpen },
    { id: 'coffee', label: 'Café', icon: Coffee },
    { id: 'gamepad', label: 'Jogos', icon: Gamepad2 },
    { id: 'music', label: 'Música', icon: Music },
    { id: 'utensils', label: 'Jantar', icon: Utensils },
    { id: 'flower', label: 'Descanso', icon: Flower2 },
    { id: 'gift', label: 'Presente', icon: Gift },
    { id: 'gem', label: 'Mimo Especial', icon: Gem },
    { id: 'smile', label: 'Relaxar', icon: Smile },
    { id: 'trophy', label: 'Conquista', icon: Trophy },
    { id: 'heart', label: 'Autocuidado', icon: Heart },
];

export default function AppIcon({ name, className = 'w-5 h-5', defaultIcon: Default = Moon }) {
    if (!name) return <Default className={className} />;
    const Component = ICON_MAP[name.toLowerCase()] || ICON_MAP[name] || Default;
    return <Component className={className} />;
}
